server:
  port: 8080
#spring:
#  datasource:
#    url: jdbc:mysql://rm-2zeuvr088920ann15io.mysql.rds.aliyuncs.com:3306/information_schema?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
#    username: root
#    password: kb34M2051
#    driver-class-name: com.mysql.jdbc.Driver
#
#mybatis:
#  mapper-locations: classpath:**/mapper/*.xml

logging:
  level:
    com.icezhg.codegenerator.mapper: debug
